### ISSUE TITLE
train on new dataset

### ISSUE THREAD

**Issue by samrat213** [hongfz16/EVA3D#9]
hi,
I want to train this model on a similar dataset to deepfashion.
I have calculated keypoint info using openpose(only 18 keypoints), you seems to have more taken keypoint info as input. which method did you use
I am producing segmentation mask using u2net.

in smpl.pkl you have camera parameters and other information, how have you calculated it?

Any other suggestions on how should I proceed?

**Comment by hongfz16** [comment]
Hi. You are actually looking for a way to estimate SMPL and camera from single images. I would recommend [smplify-x](https://github.com/vchoutas/smplify-x), since it is my choice for preprocessing the DeepFashion dataset. If you want to try some feed-forward methods, [mmhuman3d](https://github.com/open-mmlab/mmhuman3d) might be a good starting point to try different models.

**Comment by hongfz16** [comment]
Closing. Feel free to reopen it if you have further questions.
